//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtraDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL007
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL007()
        {
            this.TBL128 = new HashSet<TBL128>();
        }
    
        public int ID { get; set; }
        public System.Guid CardGuide { get; set; }
        public string CardCode { get; set; }
        public string ProductName { get; set; }
        public string LatinName { get; set; }
        public string StatementName { get; set; }
        public string Source { get; set; }
        public Nullable<short> StockProduct { get; set; }
        public Nullable<bool> ListAlternatives { get; set; }
        public System.Guid GroupGuid { get; set; }
        public Nullable<System.Guid> DefaultCurrency { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public byte Security { get; set; }
        public string Specification { get; set; }
        public byte ProductType { get; set; }
        public Nullable<int> ItemColor { get; set; }
        public Nullable<short> DefaultUnit { get; set; }
        public bool NotActive { get; set; }
        public bool NotTaxable { get; set; }
        public bool NotDiscountable { get; set; }
        public string Custom { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Unit { get; set; }
        public string Unit2 { get; set; }
        public string Unit3 { get; set; }
        public string Barcode { get; set; }
        public string Barcode2 { get; set; }
        public string Barcode3 { get; set; }
        public double Weight { get; set; }
        public double Value { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Hieght { get; set; }
        public double Weight2 { get; set; }
        public double Value2 { get; set; }
        public double Length2 { get; set; }
        public double Width2 { get; set; }
        public double Hieght2 { get; set; }
        public double Weight3 { get; set; }
        public double Value3 { get; set; }
        public double Length3 { get; set; }
        public double Width3 { get; set; }
        public double Hieght3 { get; set; }
        public bool IsAssets { get; set; }
        public Nullable<System.DateTime> DefaultExpiryDate { get; set; }
        public Nullable<double> Factor2 { get; set; }
        public Nullable<double> Factor3 { get; set; }
        public Nullable<double> TaxRatio { get; set; }
        public Nullable<double> MaxLimit { get; set; }
        public Nullable<double> MinLimit { get; set; }
        public double AgentPrice { get; set; }
        public double AgentPrice2 { get; set; }
        public double AgentPrice3 { get; set; }
        public double AgentPriceTax { get; set; }
        public Nullable<System.Guid> AgentPriceCurrency { get; set; }
        public double WholePrice { get; set; }
        public double WholePrice2 { get; set; }
        public double WholePrice3 { get; set; }
        public double WholePriceTax { get; set; }
        public Nullable<System.Guid> WholePriceCurrency { get; set; }
        public double EndUserPrice { get; set; }
        public double EndUserPrice2 { get; set; }
        public double EndUserPrice3 { get; set; }
        public double EndUserPriceTax { get; set; }
        public Nullable<System.Guid> EndUserPriceCurrency { get; set; }
        public double Price5Item { get; set; }
        public double Price5Item2 { get; set; }
        public double Price5Item3 { get; set; }
        public double Price5ItemTax { get; set; }
        public Nullable<System.Guid> Price5ItemCurrency { get; set; }
        public double Price6Item { get; set; }
        public double Price6Item2 { get; set; }
        public double Price6Item3 { get; set; }
        public double Price6ItemTax { get; set; }
        public Nullable<System.Guid> Price6ItemCurrency { get; set; }
        public double Price7Item { get; set; }
        public double Price7Item2 { get; set; }
        public double Price7Item3 { get; set; }
        public double Price7ItemTax { get; set; }
        public Nullable<System.Guid> Price7ItemCurrency { get; set; }
        public double StanderCost { get; set; }
        public double StanderCost2 { get; set; }
        public double StanderCost3 { get; set; }
        public double StanderCostTax { get; set; }
        public Nullable<System.Guid> StanderCostCurrency { get; set; }
        public int CardOrder { get; set; }
        public double Points { get; set; }
        public double Points2 { get; set; }
        public double Points3 { get; set; }
        public Nullable<System.Guid> Category01 { get; set; }
        public Nullable<System.Guid> Category02 { get; set; }
        public Nullable<System.Guid> Category03 { get; set; }
        public Nullable<System.Guid> Category04 { get; set; }
        public Nullable<System.Guid> Category05 { get; set; }
        public byte[] CardImage { get; set; }
        public Nullable<System.Guid> ByUser { get; set; }
        public Nullable<System.Guid> ByGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL128> TBL128 { get; set; }
    }
}
