//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtraDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL128
    {
        public int ID { get; set; }
        public System.Guid CardGuide { get; set; }
        public int CardNumber { get; set; }
        public byte Security { get; set; }
        public string UnitName { get; set; }
        public string LatinName { get; set; }
        public byte MainUnit { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public double AgentPrice { get; set; }
        public double WholePrice { get; set; }
        public double EndUserPrice { get; set; }
        public double Price5Item { get; set; }
        public double Price6Item { get; set; }
        public double Price7Item { get; set; }
        public double StanderCost { get; set; }
        public string Barcode { get; set; }
        public string Notes { get; set; }
        public System.Guid MainGuide { get; set; }
    
        public virtual TBL007 TBL007 { get; set; }
    }
}
